name: Formatting

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab


jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: |
          ruff check
          ruff format --check
